module ElasticGraph
  class Indexer
    class ConfigSupertype
      extend Support::Config::ClassMethods[Config]

      attr_reader latency_slo_thresholds_by_timestamp_in_ms: ::Hash[::String, ::Integer]
      attr_reader skip_derived_indexing_type_updates: ::Hash[::String, ::Set[::String]]
      attr_reader skip_record_validation_for: ::Hash[::String, ::Float]

      def initialize: (
        ?latency_slo_thresholds_by_timestamp_in_ms: ::Hash[::String, ::Integer],
        ?skip_derived_indexing_type_updates: ::Hash[::String, ::Set[::String]],
        ?skip_record_validation_for: ::Hash[::String, ::Float]) -> void

      def with: (
        ?latency_slo_thresholds_by_timestamp_in_ms: ::Hash[::String, ::Integer],
        ?skip_derived_indexing_type_updates: ::Hash[::String, ::Set[::String]],
        ?skip_record_validation_for: ::Hash[::String, ::Float]) -> Config

      def self.members: () -> ::Array[::Symbol]
    end

    class Config < ConfigSupertype
      private

      def convert_values: (
        latency_slo_thresholds_by_timestamp_in_ms: untyped,
        skip_derived_indexing_type_updates: untyped,
        skip_record_validation_for: untyped
      ) -> ::Hash[::Symbol, untyped]
    end
  end
end
